# Random Forest Classifier
This notebook reviews the basic concepts you need to know in order to
sucessfully create a random forest model. We will use the
```RandomForestClassifier``` from **sklearn**.

We start by importing some functions

In [7]:
#Import the train_test_split function
from sklearn.ensemble import RandomForestClassifier

#Import the function that creates the data we will split
from mlb_misc_functions import create_clf_table_1

Now, we will create our modeling table (```model_data```). This is a dummy/fake table that resembles the format of real data. The table has 7 columns. 1 column is a unique identifier, 5 columns are features, and the last column is the target. In this case the target takes the values 0 and 1.

In [8]:
#Call the funciton that creates the table. 10,000 rows
model_data = create_clf_table_1(10000)
model_data.head()

row_id  feature_1  feature_2  feature_3  feature_4  feature_5  target
0       0         -1          1         -6        -10          8       0
1       1         -4          3         -1         -8         -6       0
2       2         -8          1          9          3          8       1
3       3          1          7          6          3         -4       1
4       4         -3         -2          4         -6         -3       0

Now, we will split the table into training and testing set. For more info about how to split your data into training and testing click [here](https://github.com/sebaszb/DataScienceSimple/blob/master/machine_learning_basics/training_testing_split.ipynb).

In [9]:
#Import the train_test_split function
from sklearn.model_selection import train_test_split

model_train, model_test = train_test_split(model_data, test_size=0.20, random_state=11)

In [41]:
features = ["feature_1", "feature_2", "feature_3", "feature_4", "feature_5"]
target = ["target"]
train_x = model_train[features].values
#train_y = model_train[target].values
train_y = np.ravel(model_train[target].values)

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
rf_clf = RandomForestClassifier()
rf_clf.fit(train_x, train_y)

/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [60]:
rf_clf.predict(np.array([[1, 1, 1, 1, 1]]))

array([0])

In [55]:
train_x[1:2]

array([[ -7,  -1, -10,  -8,   7]])

In [58]:
np.array[[1, 1, 1, 1, 1]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [56]:
train_x[0]

array([ -8,  -7,   0, -10,   7])